# Generated by Django 3.1.6 on 2021-02-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='full_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='thumb',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
